### ISSUE TITLE
Font value is incorrect

### ISSUE THREAD

**Issue by emily060866** [emily060866/responsive-header#1]
Hello! 

Markbot tells me that it expects a different value inside of font in my 320px html, however I wrote exactly the one you put on your website. 

@thomasjbradley

<img width="551" alt="screenshot 2018-11-20 20 36 05" src="https://user-images.githubusercontent.com/43139115/48813318-51a1a400-ed04-11e8-8a6f-47f8670d30a9.png">

```css
html {
  -moz-text-size-adjust: 100%;
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
  text-size-adjust: 100%;

  box-sizing: border-box;
  font: normal 100%/1.3 sans-serif;
  font-family: Ubuntu, sans-serif;
  line-height: 1.3;
}
```

thank you,
Emily

**Comment by thomasjbradley** [comment]
You can always look inside the `.markbot.yml` to see exactly what Markbot wants, for this assignment it’s:

```css
html {
  font: normal 100%/1.3 Ubuntu, sans-serif;
}
```
